POST http://localhost:3000/messages HTTP/1.1
content-type: application/json

{
    "content": "hi there"
}

### Get messages
GET http://localhost:3000/messages HTTP/1.1

### Get message by id
GET http://localhost:3000/messages/473 HTTP/1.1